# Basic Python

## 1. Split this string

In [1]:
s = "Hi there Sam!"

In [2]:
print(s.split())

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [3]:
planet = "Earth"
diameter = 12742

In [4]:
print("The diameter of {planet} is {distance} kilometeres".format(planet="Earth",distance=12742))

The diameter of Earth is 12742 kilometeres


## 3. In this nest dictionary grab the word "hello"

In [5]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [6]:
print(d['k1'][3]['tricky'][3]['target'][3])

hello


# Numpy

In [7]:
import numpy as np

## 4.1 Create an array of 10 zeros? 


In [10]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
np.ones(10)*0

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## 4.2 Create an array of 10 fives?

In [12]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [13]:
print( np.arange(20,35,2) )

[20 22 24 26 28 30 32 34]


In [14]:
arr1 = np.arange(20,35,2)
print(arr1)

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [15]:
arr3 = np.arange(0,9).reshape(3,3)
print(arr3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 7. Concatenate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [16]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c=np.concatenate((a,b),axis=0)
print(c)

[1 2 3 4 5 6]


# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [17]:
import pandas as pd
data=[["Srinath",96],["Aravinth",12],["Yukan",119]]
data1=pd.DataFrame(data,columns=["name","rollno"])
print(data1)

       name  rollno
0   Srinath      96
1  Aravinth      12
2     Yukan     119


## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [20]:
d9=pd.date_range(start="1-01-2023",end="10-02-2023",freq="8h")
print(d9)

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 08:00:00',
               '2023-01-01 16:00:00', '2023-01-02 00:00:00',
               '2023-01-02 08:00:00', '2023-01-02 16:00:00',
               '2023-01-03 00:00:00', '2023-01-03 08:00:00',
               '2023-01-03 16:00:00', '2023-01-04 00:00:00',
               ...
               '2023-09-29 00:00:00', '2023-09-29 08:00:00',
               '2023-09-29 16:00:00', '2023-09-30 00:00:00',
               '2023-09-30 08:00:00', '2023-09-30 16:00:00',
               '2023-10-01 00:00:00', '2023-10-01 08:00:00',
               '2023-10-01 16:00:00', '2023-10-02 00:00:00'],
              dtype='datetime64[ns]', length=823, freq='8H')


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [21]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [22]:
data2=pd.DataFrame(lists,columns=["s.no","Name","marks"])
print(data2)

   s.no Name  marks
0     1  aaa     22
1     2  bbb     25
2     3  ccc     24
